use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :garrahan, GarrahanWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure Guardian
config :garrahan, Garrahan.Auth.Guardian,
  issuer: "garrahan",
  secret_key: {:system, "GUARDIAN_SECRET_KEY"}

config :garrahan,
  user_verification_salt: {:system, "USER_VERIFICATION_SALT"}

